services:
  mongo:
    image: mongo:latest
    container_name: MealMeter-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
